# Markdownlint configuration
config:
  # Allow HTML tags (useful for rich documentation)
  no-inline-html: false

  # Allow bare URLs (useful for reference documentation)
  no-bare-urls: false

  # Be more lenient with emphasis markers
  no-emphasis-as-heading: false

  # Allow multiple blank lines for document structure
  no-multiple-blanks: false

  # Allow trailing punctuation in headers
  no-trailing-punctuation: false

  # Allow first line to not be a top level header
  first-line-heading: false

  # Disable line length check for code blocks
  MD013:
    line_length: 120
    code_blocks: false
    tables: false

# Fix issues automatically where possible
fix: true

# Ignore patterns
ignores:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "CLAUDE.md"
  - ".beads/**"
  - ".claude/**"
