---
name: Security Vulnerability (Low Severity)
description: Report a low-severity security issue (For critical issues, use Security Advisories)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        ## Important Security Notice

        **For critical, high, or medium severity vulnerabilities, please use
        [GitHub Security Advisories](https://github.com/Recipe-Web-App/system-control/security/advisories/new)
        instead of this public issue template.**

        This template is only for **low-severity** security issues that don't pose immediate risk.

  - type: checkboxes
    id: severity_confirmation
    attributes:
      label: Severity Confirmation
      description: Please confirm this is a low-severity issue
      options:
        - label: I confirm this is a LOW severity issue (best practice violation, minor information leak, etc.)
          required: true
        - label: I understand that critical/high/medium vulnerabilities should be reported privately via Security Advisories
          required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear description of the security issue
      placeholder: Describe the security issue
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Information Disclosure (minor)
        - Insecure Default Configuration
        - Missing Security Header
        - Best Practice Violation
        - Verbose Error Messages
        - Documentation Security Issue
        - Dependency with Low-Severity CVE
        - Other (Low Severity)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - CLI Commands
        - Configuration Management
        - Logging System
        - Plugin System
        - External Integrations
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this issue?
      placeholder: |
        Describe what could happen if this issue is exploited
        (Remember: this should be low-impact for this template)
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Configure '...'
        2. Run command '...'
        3. Observe '...'
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: Do you have a suggestion for fixing this issue?
      placeholder: Describe your suggested fix or mitigation

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - Python version:
        - CLI version:
        - OS:
        - Installation method:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional context or references

  - type: checkboxes
    id: terms
    attributes:
      label: Responsible Disclosure
      description: Please confirm the following
      options:
        - label: I have not publicly disclosed this vulnerability elsewhere
          required: true
        - label: I agree to give the maintainers reasonable time to address this issue
          required: true
