"""Init command for initializing a new project."""

from __future__ import annotations

from pathlib import Path

import structlog
import typer
from rich.console import Console
from rich.panel import Panel

app = typer.Typer(help="Initialize a new system control project.")
console = Console()
logger = structlog.get_logger()


@app.callback(invoke_without_command=True)
def init(
    ctx: typer.Context,
    path: Path | None = typer.Argument(
        None,
        help="Path to initialize the project in. Defaults to current directory.",
    ),
    template: str = typer.Option(
        "default",
        "--template",
        "-t",
        help="Template to use for initialization.",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing configuration.",
    ),
) -> None:
    """Initialize a new system control project configuration."""
    if ctx.invoked_subcommand is not None:
        return

    target_path = path or Path.cwd()
    config_file = target_path / ".ops.yaml"

    logger.info("Initializing project", path=str(target_path), template=template)

    if config_file.exists() and not force:
        console.print(f"[yellow]Configuration already exists at {config_file}[/yellow]")
        console.print("Use --force to overwrite.")
        raise typer.Exit(code=1)

    # Create basic configuration
    default_config = """# System Control CLI Configuration
# Generated by ops init

version: "1.0"

# Environment configuration
environment: development

# Profiles
profiles:
  default:
    debug: false
    log_level: INFO

# Plugin configuration
plugins:
  enabled:
    - core
"""

    config_file.write_text(default_config)

    console.print(
        Panel(
            f"[green]Project initialized successfully![/green]\n\n"
            f"Configuration created at: {config_file}\n\n"
            f"Next steps:\n"
            f"  1. Edit {config_file} to customize your configuration\n"
            f"  2. Run [bold]ops status[/bold] to verify setup",
            title="ops init",
            border_style="green",
        )
    )

    logger.info("Project initialized", config_file=str(config_file))
