"""Init command for initializing a new project."""

from __future__ import annotations

from pathlib import Path

import structlog
import typer
from rich.console import Console
from rich.panel import Panel

app = typer.Typer(help="Initialize a new system control project.")
console = Console()
logger = structlog.get_logger()

# XDG-compliant config location
CONFIG_DIR = Path.home() / ".config" / "ops"
CONFIG_FILE = CONFIG_DIR / "config.yaml"


@app.callback(invoke_without_command=True)
def init(
    ctx: typer.Context,
    template: str = typer.Option(
        "default",
        "--template",
        "-t",
        help="Template to use for initialization.",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing configuration.",
    ),
) -> None:
    """Initialize system control configuration in ~/.config/ops/."""
    if ctx.invoked_subcommand is not None:
        return

    logger.info("Initializing config", path=str(CONFIG_FILE), template=template)

    # Create config directory if it doesn't exist
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    if CONFIG_FILE.exists() and not force:
        console.print(f"[yellow]Configuration already exists at {CONFIG_FILE}[/yellow]")
        console.print("Use --force to overwrite.")
        raise typer.Exit(code=1)

    # Create basic configuration
    default_config = """# System Control CLI Configuration
# Generated by ops init

version: "1.0"

# Environment configuration
environment: development

# Profiles
profiles:
  default:
    debug: false
    log_level: INFO

# Plugin configuration
plugins:
  enabled:
    - core
"""

    CONFIG_FILE.write_text(default_config)

    console.print(
        Panel(
            f"[green]Configuration initialized successfully![/green]\n\n"
            f"Configuration created at: {CONFIG_FILE}\n\n"
            f"Next steps:\n"
            f"  1. Edit {CONFIG_FILE} to customize your configuration\n"
            f"  2. Run [bold]ops status[/bold] to verify setup",
            title="ops init",
            border_style="green",
        )
    )

    logger.info("Configuration initialized", config_file=str(CONFIG_FILE))
